apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: jarvis
  name: jarvis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jarvis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      labels:
        io.kompose.network/jarvis-default: "true"
        io.kompose.service: jarvis
    spec:
      containers:
        - image: jarvis
          name: jarvis-app
          ports:
            - containerPort: 8080
            - containerPort: 50051
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
      restartPolicy: Always

