apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jarvis-deployment.yaml
- jarvis-service.yaml
- jarvis-default-networkpolicy.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pv.yaml
- mysql-pvc.yaml

images:
- name: jarvis
  newName: lucasgoisdev/jarvis
  newTag: 817328bc89344149570c70b2174e0ddee661850b
