apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jarvis-deployment.yaml
- jarvis-service.yaml
- jarvis-default-networkpolicy.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pvc.yaml

images:
- name: jarvis
  newName: lucasgoisdev/jarvis
  newTag: 71d1269b3dbd8d31ee34a00b06d819df35b76a1c
