apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jarvis-deployment.yaml
- jarvis-service.yaml
- jarvis-default-networkpolicy.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-claim0-persistentvolumeclaim.yaml

images:
- name: jarvis
  newName: lucasgoisdev/jarvis
  newTag: baf1e8d6bcd06f6ca90c7acd7c221608ee1ff151
