apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jarvis-deployment.yaml
- jarvis-service.yaml
- jarvis-default-networkpolicy.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pv.yaml
- mysql-pvc.yaml

images:
- name: jarvis
  newName: lucasgoisdev/jarvis
  newTag: 4e8e4bf8166da51785c344be3eb7f918c5efef8d
