apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jarvis-deployment.yaml
- jarvis-service.yaml
- jarvis-default-networkpolicy.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pvc.yaml

images:
- name: jarvis
  newName: lucasgoisdev/jarvis
  newTag: 2f54f88a3fd35bfc3ba4f816eed368cb569313a2
