apiVersion: v1
kind: Service
metadata:
  name: jarvis-mysql
  labels:
    app: jarvis
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: jarvis
    tier: mysql
