apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis-mysql
  labels:
    app: jarvis
spec:
  selector:
    matchLabels:
      app: jarvis
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jarvis
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: jarvis
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: jarvis
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1500m"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistence-storage
      restartPolicy: Always
      volumes:
        - name: mysql-persistence-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
